### ISSUE TITLE
add julia package install into docker

### ISSUE THREAD

**Issue by Elchin** [uaf-arctic-eco-modeling/dvm-dos-tem#572]
We need to install a specific version. This is how I am currently doing it
cd /opt 
wget https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.3-linux-x86_64.tar.gz
tar -xzf  julia…..tar.gz
ln -s /opt/julia-1.7.3/bin/julia /usr/local/bin/julia

**Comment by tobeycarman** [comment]
Discussed this with @amullen01 at the last few minutes of the workshop, but if you find yourself needing to install packages in the Docker containers repeatedly as you wait for the changes to be accepted upstream, you can bundle your customizations into a script that you execute each time you bring up the Docker stack. For example:

```bash
#!/bin/bash

echo "Run my custom setup"

echo "Downloading and installing Julia..."
wget https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.3-linux-x86_64.tar.gz
tar -xzf julia-1.7.3-linux-x86_64.tar.gz
cp -r julia-1.7.3 /opt/
ln -s /opt/julia-1.7.3/bin/julia /usr/local/bin/julia

echo "Installing stuff in Julia..."
echo 'using Pkg; Pkg.add("Mads@1.3.10")' | julia
```
You need to take the appropriate cautions with respect to running as root or not depending on your arrangement and what packages you are working with.

Then you can simply run that script after you bring up your Docker container. This is still a nusciance since it takes so long to install some things, but it might be a little bit helpful. There are two other approaches you could take as interim measures until the branch with these new dependencies is merged to master:
 
 1. Add the packages to the Docker file (you'll have to handle the modifications and possible conflicts when you pull updates from upstream)
 2. Add a custom image to the Dockerfile (or add another Dockerfile with your custom image)
 
To actually resolve this issue, we will need to wrap up the calibration code, modify the Docker file appropriately and merge the branch upstream.

**Comment by tobeycarman** [comment]
Entirely possible to put plenty of other stuff in your customization script as well, for example customizations to `.bashrc` or `.vimrc`, etc...

**Comment by tobeycarman** [comment]
@amullen01, (@Elchin, @valeriabriones this is likely of interest to you as well) I realized that a perhaps better way to handle this is as follows:

1. amend the docker file so as to address the changes you need for your work (in this case, add the commands to download and install `Julia`, in a section of the Docker file that is being done as the root user).
2. make a commit on your topic branch with these changes
3. build new images from this commit
4. change the `V_TAG` variable in your `.env` file so that when you run `docker compose up` it brings up your new images.

You can keep many versions of the images around (as long as you have space for them) and easily switch which containers you are running by simply editing the `.env` file.

This solution has several advantages over the previous option:
 - you don't have to be constantly re-running the expensive steps of downloading and re-installing packages
 - your topic branch is one step closer to being ready to merge as it will have the Docker file amended appropriately. 
 - this solution works for `pip` installed stuff too - you would modify the requirements file appropriately, and commit it (likely with the Dockerfile above) and your images built from these commits should have all the dependencies included
