### ISSUE TITLE
Confirm that the "seed path" setting in user's config (yaml) file is being honored in all cases

### ISSUE THREAD

**Issue by tobeycarman** [uaf-arctic-eco-modeling/dvm-dos-tem#667]
Make sure that the seed path that the user selects is being honored for seeding parameter values. Need to check this for both the Sensitivity class and the MadsTEMDriver class.

**Comment by jsclein-uaf** [comment]
YES, I tried changing the seed_path during a 'ca' run and it did not work
and YES
having this option available during the 'sa' runs would be great and overall for all calibrating so that you could beupdating your parameter files in a separate location, and not have to worry when you are updating a version of TEM

**Comment by Benjamin-Maglio** [comment]
Tested commit `71429f2929c837f96a36c430422b991245b4faee` and seed path is honored for CA. Working on honoring for SA now.

**Comment by jsclein-uaf** [comment]
thanks Ben, looking forward to seed path working in SA run too... thanks for all your help and hard work. joy

**Comment by tobeycarman** [comment]
fixed with PR #699
